//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webTestEX.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("webTestEX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   자바스크립트에서 변수 x를 정의해보자. 어떤 키워드를 사용하여 변수를 정의할 수 있을까? := let x;
        ///const 키워드는 무엇을 정의하기 위해 사용? := 상수
        ///숫자를 가지는 JS의 데이터 타입은? := 수치형
        ///텍스트 데이터를 가지는 JS의 데이터 타입은? := 문자열
        ///true와 false 값을 가지는 JS의 데이터 타입은? := 부울형
        ///빈 값 또는 정의되지 않은 값을 가지는 JS의 데이터 타입은? := undefined
        ///객체를 가지는 JS의 데이터 타입은? := 객체형
        ///문자열들을 대문자로 변경 하는 메서드는? := toUpperCase()
        ///템플릿 리터럴 문자열을 사용하는 기호는? := $
        ///${변수명}과 같은 형식으로 변수를 삽입하는 방법은? := 템플릿 리터럴
        ///객체형을 선언할때 사용하는 기호는 ? := {}
        ///값과 타입이 모두 같은지 비교하는 연산자는? := ===
        ///값이나 타입이 다른지 비교하는 연산자는? := !==
        ///값이 같은지 비교하는 연산자는? := ==
        ///console[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 새_텍스트_문서 {
            get {
                return ResourceManager.GetString("새 텍스트 문서", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] 웹프_문제_테스트 {
            get {
                object obj = ResourceManager.GetObject("웹프 문제 테스트", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] 웹프_문제_테스트_deps {
            get {
                object obj = ResourceManager.GetObject("웹프 문제 테스트.deps", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] 웹프_문제_테스트_runtimeconfig {
            get {
                object obj = ResourceManager.GetObject("웹프 문제 테스트.runtimeconfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
